#!/bin/bash

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

cd ${APP_HOME}
git pull || exit 1
chown -Rf nginx:nginx ${WWW_ROOT}
