#!/bin/bash

if [ -z "$MYSQL_HOST" ]; then
  echo 'MYSQL_HOST not defined'
  exit 1
fi
if [ -z "$MYSQL_USER" ]; then
  echo 'MYSQL_USER not defined'
  exit 1
fi
if [ -z "$MYSQL_DB" ]; then
  echo 'MYSQL_DB not defined'
  exit 1
fi

if [ -d "$APP_DB" ]; then

  echo "## Restoring Database"

  echo "Creating database: ${MYSQL_DB}"
  [ -z "$MYSQL_ROOT_PW" ] || ROOTPW="-p${MYSQL_ROOT_PW}"
  mysql -h "${MYSQL_HOST}" -u root "$ROOTPW" -e \
    "DROP DATABASE IF EXISTS ${MYSQL_DB}; \
     CREATE DATABASE ${MYSQL_DB}; \
     GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_USER_PW}';"

  for i in `ls ${APP_DB}/*.sql`; do
    echo "Loading: ${i}"
    [ -z "$MYSQL_USER_PW" ] || USERPW="-p${MYSQL_USER_PW}"
    mysql -h "${MYSQL_HOST}" -u "$MYSQL_USER" "$USERPW" "$MYSQL_DB" < "${i}"
    #mysql -u socialengine -pyNW4TKgr68wsLA socialengine < socialengine.sql
  done

else
  echo "Can't restore database: ${APP_DB} not found"
  exit 1
fi
